export const projects = [
    {
        slug: 'jordanville',
        name: 'Holy Trinity Monastery',
        titleHtml: 'Holy Trinity<br>Monastery',
        location: 'Jordanville, NY',
        locationFull: 'Jordanville, New York',
        type: 'Powerful Monastic and Spiritual Legacy',
        subtitle: 'Powerful monastic and spiritual legacy',
        description: "Holy Trinity Monastery is a major pilgrim destination, spiritual center, and historic site. The monastery is known all over the world in Orthodox Christian circles for its publishing activity in the Cold War period, the seminary on the monastery's grounds, and the many highly influential church leaders and luminaries that lived and worked there. The monastery and seminary have used Eyekonika's glass engravings as gifts for donors, important guests, and offer them for pilgrims to buy in the monastery gift shop.",
        color: '#12172e',
        image: '/images/holy_trinity_monastery_front_photo.JPG',
        watermark: [['H','O','L','Y'], ['T','R','I','N']],
        gridClass: 'project-grid--jordanville',
        gallery: [
            { src: '/images/Jordanville_detail_2.JPG', alt: 'Holy Trinity Monastery — engraving detail' },
            { src: '/images/detail_holy_trinity_monastery_1.JPG', alt: 'Holy Trinity Monastery — engraving detail' },
            { src: '/images/holy_trinity_monastery_front_photo.JPG', alt: 'Holy Trinity Monastery — exterior' },
            { src: '/images/side_perspective_Jordanville_3.JPG', alt: 'Holy Trinity Monastery — side perspective' },
        ],
    },
    {
        slug: 'lakewood',
        name: 'St. Alexander Nevsky Cathedral',
        titleHtml: 'St. Alexander<br>Nevsky Cathedral',
        location: 'Howell, NJ',
        locationFull: 'Howell, New Jersey',
        type: 'Thriving Russian Orthodox Parish',
        subtitle: 'Thriving Russian Orthodox Parish',
        description: "St. Alexander Nevsky's is a thriving Russian Orthodox parish with a rich history and beautifully built cathedral. Eyekonika's model of the church is available at the parish store.",
        color: '#0e1e30',
        image: '/images/project_photos/Lakewood_main_image.JPG',
        watermark: [['L','A','K','E'], ['W','O','O','D']],
        gallery: [
            { src: '/images/project_photos/Lakewood_main_image.JPG', alt: 'St. Alexander Nevsky Cathedral' },
            { src: '/images/project_photos/Lakewood_top_down_with_double_lighting.JPG', alt: 'St. Alexander Nevsky Cathedral, top-down view with double lighting' },
            { src: '/images/project_photos/St. Alexander Nevsky Cathedral.JPG', alt: 'St. Alexander Nevsky Cathedral' },
            { src: '/images/project_photos/unusual_angle_lakewood_model.JPG', alt: 'St. Alexander Nevsky Cathedral, unusual angle' },
        ],
    },
    {
        slug: 'st-tikhons',
        name: "St. Tikhon's Monastery",
        titleHtml: "St. Tikhon's<br>Monastery",
        location: 'Waymart, PA',
        locationFull: 'Waymart, Pennsylvania',
        type: 'Oldest Orthodox Monastery in America',
        subtitle: 'Oldest Orthodox Monastery in the USA',
        description: "St. Tikhon's Monastery is the oldest operating Orthodox Christian monastery in the United States of America. Eyekonika worked with the abbot through several iterations to model the front of the main monastery church, capturing the iconic building's entrance and front icon.",
        color: '#121e16',
        image: '/images/project_photos/front-detail-high-detail-st-tikhons-monastery-waymart-PA.JPG',
        thumbnail: '/images/project_photos/front-detail-waymart-PA.JPG',
        thumbPosition: 'center 20%',
        watermark: [['T','I','K','H'], ['O','N','S',' ']],
        gallery: [
            { src: '/images/gallery/2.jpg', alt: "St. Tikhon's Monastery" },
            { src: '/images/project_photos/key_image_st_tikhons-monastery-waymart_PA.JPG', alt: "St. Tikhon's Monastery, Waymart PA" },
            { src: '/images/project_photos/reverse of St. Tikhons model.JPG', alt: "St. Tikhon's Monastery model, reverse side" },
            { src: '/images/gallery/3.jpg', alt: "St. Tikhon's Monastery" },
        ],
    },
];
